/**
 * Autogenerated by Thrift Compiler (0.9.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef ThreadsTest_CONSTANTS_H
#define ThreadsTest_CONSTANTS_H

#include "ThreadsTest_types.h"



class ThreadsTestConstants {
 public:
  ThreadsTestConstants();

};

extern const ThreadsTestConstants g_ThreadsTest_constants;



#endif
